/*
 * Projeto Archiver
 * ST562 - Estrutura de Arquivos
 * Professor Dr. Celmar Guimarães da Silva
 */
package archiver;

import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Rodrigues De Biasi
 * @author Ricardo Hideki Adati Tomommitsu
 * @author Roberth Riyu Tamayose
 * @author Thiago Kaoru Alves Takehama
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        setIcon();
        
        jTextFieldArchive.getDocument().addDocumentListener(new DocumentListener() {
            
            @Override
            public void insertUpdate(DocumentEvent de) {
                updateTableArquivos();
            }
            
            @Override
            public void changedUpdate(DocumentEvent de) {
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
            }
        });
    }

    public void updateTableArquivos(){
        jTableArquivos.setModel(new Archive(jTextFieldArchive.getText()).atualizarTabela());
        jTableArquivos.getColumnModel().getColumn(1).setMaxWidth(120);
        jTableArquivos.getColumnModel().getColumn(1).setPreferredWidth(120);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelBase = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldDiretorio = new javax.swing.JTextField();
        jButtonSelecionarDiretorio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonCriar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNomeArchive = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldArquivoNovoArchive = new javax.swing.JTextField();
        jButtonSelecionarArquivoNovoArchive = new javax.swing.JButton();
        jButtonInserirArquivoNovoArchive = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArquivosNovoArchive = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonSelecionarArchive = new javax.swing.JButton();
        jTextFieldArchive = new javax.swing.JTextField();
        jButtonSelecionarArquivo = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldArquivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArquivos = new javax.swing.JTable();
        jButtonExtrairSelecionado = new javax.swing.JButton();
        jButtonExtrairTudo = new javax.swing.JButton();
        jButtonRemoverSelecionado = new javax.swing.JButton();
        jButtonRemoverTudo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkySea Archiver");
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setResizable(false);

        jPanelBase.setLayout(null);

        jPanel1.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo Archive", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jTextFieldDiretorio.setEditable(false);
        jTextFieldDiretorio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jButtonSelecionarDiretorio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSelecionarDiretorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pasta.png"))); // NOI18N
        jButtonSelecionarDiretorio.setFocusable(false);
        jButtonSelecionarDiretorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarDiretorioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nome do Archive:");

        jButtonCriar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonCriar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/criar.png"))); // NOI18N
        jButtonCriar.setText("Criar");
        jButtonCriar.setFocusable(false);
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(".sky");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Diretório:");

        jTextFieldNomeArchive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        jPanel4.setEnabled(false);
        jPanel4.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Selecionar arquivos (opcional):");

        jTextFieldArquivoNovoArchive.setEditable(false);
        jTextFieldArquivoNovoArchive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jButtonSelecionarArquivoNovoArchive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSelecionarArquivoNovoArchive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file.png"))); // NOI18N
        jButtonSelecionarArquivoNovoArchive.setFocusable(false);
        jButtonSelecionarArquivoNovoArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarArquivoNovoArchiveActionPerformed(evt);
            }
        });

        jButtonInserirArquivoNovoArchive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonInserirArquivoNovoArchive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        jButtonInserirArquivoNovoArchive.setFocusable(false);
        jButtonInserirArquivoNovoArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirArquivoNovoArchiveActionPerformed(evt);
            }
        });

        jTableArquivosNovoArchive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableArquivosNovoArchive.setFocusable(false);
        jTableArquivosNovoArchive.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTableArquivosNovoArchive);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldArquivoNovoArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelecionarArquivoNovoArchive)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInserirArquivoNovoArchive))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldArquivoNovoArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonInserirArquivoNovoArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecionarArquivoNovoArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldNomeArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSelecionarDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDiretorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSelecionarDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciar Archives Existentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jButtonSelecionarArchive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSelecionarArchive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/archive.png"))); // NOI18N
        jButtonSelecionarArchive.setFocusable(false);
        jButtonSelecionarArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarArchiveActionPerformed(evt);
            }
        });

        jTextFieldArchive.setEditable(false);
        jTextFieldArchive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jButtonSelecionarArquivo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonSelecionarArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file.png"))); // NOI18N
        jButtonSelecionarArquivo.setFocusable(false);
        jButtonSelecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarArquivoActionPerformed(evt);
            }
        });

        jButtonInserir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        jButtonInserir.setText("Inserir");
        jButtonInserir.setFocusable(false);
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Selecionar Archive:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Selecionar Arquivo:");

        jTextFieldArquivo.setEditable(false);
        jTextFieldArquivo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jTableArquivos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableArquivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableArquivos.setFocusable(false);
        jTableArquivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableArquivos);

        jButtonExtrairSelecionado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonExtrairSelecionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/extrairSelecionado.png"))); // NOI18N
        jButtonExtrairSelecionado.setText("Extrair Selecionado");
        jButtonExtrairSelecionado.setEnabled(false);
        jButtonExtrairSelecionado.setFocusable(false);
        jButtonExtrairSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtrairSelecionadoActionPerformed(evt);
            }
        });

        jButtonExtrairTudo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonExtrairTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/extrairTudo.png"))); // NOI18N
        jButtonExtrairTudo.setText("Extrair Tudo");
        jButtonExtrairTudo.setEnabled(false);
        jButtonExtrairTudo.setFocusable(false);
        jButtonExtrairTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtrairTudoActionPerformed(evt);
            }
        });

        jButtonRemoverSelecionado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonRemoverSelecionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/removerSelecionado.png"))); // NOI18N
        jButtonRemoverSelecionado.setText("Remover Selecionado");
        jButtonRemoverSelecionado.setEnabled(false);
        jButtonRemoverSelecionado.setFocusable(false);
        jButtonRemoverSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverSelecionadoActionPerformed(evt);
            }
        });

        jButtonRemoverTudo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonRemoverTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/removerTudo.png"))); // NOI18N
        jButtonRemoverTudo.setText("Remover Tudo");
        jButtonRemoverTudo.setEnabled(false);
        jButtonRemoverTudo.setFocusable(false);
        jButtonRemoverTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSelecionarArquivo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonInserir))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSelecionarArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRemoverSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExtrairTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExtrairSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRemoverTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSelecionarArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonSelecionarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonExtrairSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExtrairTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBase.add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 620);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        jPanelBase.add(jLabel2);
        jLabel2.setBounds(-21, -24, 2410, 1340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarDiretorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarDiretorioActionPerformed
        TelaSelecao sel = new TelaSelecao(this, true);
        jTextFieldDiretorio.setText(sel.showDialog(JFileChooser.DIRECTORIES_ONLY, false));
    }//GEN-LAST:event_jButtonSelecionarDiretorioActionPerformed

    private void jButtonSelecionarArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarArchiveActionPerformed
        TelaSelecao sel = new TelaSelecao(this, true);
        String dir = sel.showDialog(JFileChooser.FILES_ONLY, true);
        boolean state = false;
        if(dir != null){
            jTextFieldArchive.setText(dir);
            jButtonExtrairSelecionado.setEnabled(true);
            jButtonExtrairTudo.setEnabled(true);
            jButtonRemoverSelecionado.setEnabled(true);
            jButtonRemoverTudo.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonSelecionarArchiveActionPerformed

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        
        if(jTextFieldDiretorio.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecione um diretório!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(jTextFieldNomeArchive.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Dê um nome ao Archive!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else{
            Archive archive = new Archive();
            
            if(archive.criar(jTextFieldDiretorio.getText(), jTextFieldNomeArchive.getText())){
                for(int i = 0; i < jTableArquivosNovoArchive.getRowCount(); i++){
                    archive.inserir(jTextFieldDiretorio.getText()+File.separator+jTextFieldNomeArchive.getText().concat(".sky"), 
                                    jTableArquivosNovoArchive.getModel().getValueAt(i, 0).toString());
                }
                JOptionPane.showMessageDialog(null, "Archive criado com sucesso!", "Novo Archive", JOptionPane.INFORMATION_MESSAGE);
                
                jTextFieldDiretorio.setText("");
                jTextFieldNomeArchive.setText("");
                jTextFieldNomeArchive.transferFocusBackward();
                DefaultTableModel model = (DefaultTableModel)jTableArquivosNovoArchive.getModel();
                model.setRowCount(0);
            }else{
                JOptionPane.showMessageDialog(null, "Erro na criação do Archive.\nJá existe um Archive com o mesmo nome no diretório especificado.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonCriarActionPerformed

    private void jButtonExtrairSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtrairSelecionadoActionPerformed
        Archive archive = new Archive(jTextFieldArchive.getText());
        TelaSelecao sel = new TelaSelecao(this, true);
        if(!jTableArquivos.getSelectionModel().isSelectionEmpty()){
            String dir = sel.showDialog(JFileChooser.DIRECTORIES_ONLY, false);
            if(dir != null){
                if(archive.extrair(jTableArquivos.getValueAt(jTableArquivos.getSelectedRow(), 0).toString(), dir)){
                    JOptionPane.showMessageDialog(null, "Arquivo extraído com sucesso!", "Extrair Selecionado", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro na extração do arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um arquivo da lista!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExtrairSelecionadoActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        Archive archive = new Archive();
        if(jTextFieldArchive.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecione um archive!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else if(jTextFieldArquivo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selecione um arquivo!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else if(!archive.inserir(jTextFieldArchive.getText(), jTextFieldArquivo.getText())){
            JOptionPane.showMessageDialog(null, "Arquivo excede tamanho máximo!\nMáximo: 1GB", "Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            jTextFieldArquivo.setText("");
            updateTableArquivos();   
        }
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonExtrairTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtrairTudoActionPerformed
        Archive archive = new Archive(jTextFieldArchive.getText());
        TelaSelecao sel = new TelaSelecao(this, true);
        if(jTableArquivos.getRowCount() != 0){
            String dir = sel.showDialog(JFileChooser.DIRECTORIES_ONLY, false);
            if(dir != null){
                if(archive.extrairTudo(dir)){
                   JOptionPane.showMessageDialog(null, "Arquivos extraídos com sucesso!", "Extrair Tudo", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro na extração dos arquivos!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Archive vazio!\nNada a extrair.", "Extrair Tudo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExtrairTudoActionPerformed

    private void jButtonRemoverSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverSelecionadoActionPerformed
        Archive archive = new Archive(jTextFieldArchive.getText());  
        if(!jTableArquivos.getSelectionModel().isSelectionEmpty()){
            if(archive.remover(jTableArquivos.getValueAt(jTableArquivos.getSelectedRow(), 0).toString())){
                JOptionPane.showMessageDialog(null, "Arquivo removido com sucesso!", "Remover Selecionado", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Erro na remoção do arquivo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            updateTableArquivos();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um arquivo da lista!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRemoverSelecionadoActionPerformed

    private void jButtonRemoverTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverTudoActionPerformed
        Archive archive = new Archive(jTextFieldArchive.getText());
        if(jTableArquivos.getRowCount() != 0){
            if(archive.removerTudo()){
                JOptionPane.showMessageDialog(null, "Arquivos removidos com sucesso!", "Remover Tudo", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Erro na remoção dos arquivos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            updateTableArquivos();
        }else{
            JOptionPane.showMessageDialog(null, "Archive vazio!\nNada a remover.", "Extrair Tudo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRemoverTudoActionPerformed

    private void jButtonSelecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarArquivoActionPerformed
        TelaSelecao sel = new TelaSelecao(this, true);
        jTextFieldArquivo.setText(sel.showDialog(JFileChooser.FILES_ONLY, false));
    }//GEN-LAST:event_jButtonSelecionarArquivoActionPerformed

    private void jButtonSelecionarArquivoNovoArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarArquivoNovoArchiveActionPerformed
        TelaSelecao sel = new TelaSelecao(this, true);
        jTextFieldArquivoNovoArchive.setText(sel.showDialog(JFileChooser.FILES_ONLY, false));
    }//GEN-LAST:event_jButtonSelecionarArquivoNovoArchiveActionPerformed

    private void jButtonInserirArquivoNovoArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirArquivoNovoArchiveActionPerformed
        if(!jTextFieldArquivoNovoArchive.getText().equals("")){
            Arquivo arquivo = new Arquivo(jTextFieldArquivoNovoArchive.getText());
            int verif = jTableArquivosNovoArchive.getModel().getRowCount();
            jTableArquivosNovoArchive.setModel(arquivo.atualizarTabela(jTableArquivosNovoArchive.getModel()));
            jTableArquivosNovoArchive.getColumnModel().getColumn(1).setMaxWidth(120);
            jTableArquivosNovoArchive.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTextFieldArquivoNovoArchive.setText("");
            if(verif == jTableArquivosNovoArchive.getModel().getRowCount()){
                JOptionPane.showMessageDialog(null, "Arquivo excede tamanho máximo!\nMáximo: 1GB", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um arquivo!", "Novo Archive", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInserirArquivoNovoArchiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JButton jButtonExtrairSelecionado;
    private javax.swing.JButton jButtonExtrairTudo;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonInserirArquivoNovoArchive;
    private javax.swing.JButton jButtonRemoverSelecionado;
    private javax.swing.JButton jButtonRemoverTudo;
    private javax.swing.JButton jButtonSelecionarArchive;
    private javax.swing.JButton jButtonSelecionarArquivo;
    private javax.swing.JButton jButtonSelecionarArquivoNovoArchive;
    private javax.swing.JButton jButtonSelecionarDiretorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableArquivos;
    private javax.swing.JTable jTableArquivosNovoArchive;
    private javax.swing.JTextField jTextFieldArchive;
    private javax.swing.JTextField jTextFieldArquivo;
    private javax.swing.JTextField jTextFieldArquivoNovoArchive;
    private javax.swing.JTextField jTextFieldDiretorio;
    private javax.swing.JTextField jTextFieldNomeArchive;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
    }
}
